# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python Training\Python_Script\AutoMask\AutoMask.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore,  QtWidgets
from PyQt5.QtWidgets import QFileDialog

class Ui_QWidget(object):
    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.resize(673, 298)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QWidget.sizePolicy().hasHeightForWidth())
        QWidget.setSizePolicy(sizePolicy)
        QWidget.setMaximumSize(QtCore.QSize(673, 298))
        self.groupBox = QtWidgets.QGroupBox(QWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 551, 131))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 531, 106))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.faillogEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.faillogEdit.setObjectName("fiallogEdit")
        self.horizontalLayout.addWidget(self.faillogEdit)
        self.faillogButton = QtWidgets.QPushButton(self.layoutWidget)
        self.faillogButton.setObjectName("faillogButton")
        self.horizontalLayout.addWidget(self.faillogButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.inputEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputEdit.setObjectName("inputEdit")
        self.horizontalLayout_2.addWidget(self.inputEdit)
        self.inputButton = QtWidgets.QPushButton(self.layoutWidget)
        self.inputButton.setObjectName("inputButton")
        self.horizontalLayout_2.addWidget(self.inputButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.outputEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.outputEdit.setObjectName("outputEdit")
        self.horizontalLayout_3.addWidget(self.outputEdit)
        self.outputButton = QtWidgets.QPushButton(self.layoutWidget)
        self.outputButton.setObjectName("outputButton")
        self.horizontalLayout_3.addWidget(self.outputButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(QWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 651, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.outputBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.outputBrowser.setGeometry(QtCore.QRect(10, 22, 631, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputBrowser.sizePolicy().hasHeightForWidth())
        self.outputBrowser.setSizePolicy(sizePolicy)
        self.outputBrowser.setObjectName("outputBrowser")
        self.layoutWidget1 = QtWidgets.QWidget(QWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 10, 95, 100))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.maskButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.maskButton.setObjectName("maskButton")
        self.verticalLayout_3.addWidget(self.maskButton)
        self.exitButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_3.addWidget(self.exitButton)
        self.aboutButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout_3.addWidget(self.aboutButton)
        self.layoutWidget2 = QtWidgets.QWidget(QWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(14, 270, 651, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.statusLabel = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_4.addWidget(self.statusLabel)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "Auto Mask V1.0"))
        self.groupBox.setTitle(_translate("QWidget", "Files"))
        self.label.setText(_translate("QWidget", "Fail Log"))
        self.faillogButton.setText(_translate("QWidget", "Browse..."))
        self.label_2.setText(_translate("QWidget", "ATP Input File"))
        self.inputButton.setText(_translate("QWidget", "Browse..."))
        self.label_3.setText(_translate("QWidget", "ATP Output File"))
        self.outputButton.setText(_translate("QWidget", "Browse..."))
        self.groupBox_2.setTitle(_translate("QWidget", "Output"))
        self.maskButton.setText(_translate("QWidget", "Mask"))
        self.exitButton.setText(_translate("QWidget", "Exit"))
        self.aboutButton.setText(_translate("QWidget", "About"))
        self.statusLabel.setText(_translate("QWidget", "No fail log."))




